/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import java.util.List;
import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

public class AppTest {

    @Test
    public void testZipEqualSize() {
        List<Integer> a = Arrays.asList(1, 3, 5);
        List<Integer> b = Arrays.asList(2, 4, 6);
        List<Integer> expected = Arrays.asList(1, 2, 3, 4, 5, 6);
        assertEquals(expected, App.zip(a, b));
    }

    @Test
    public void testZipUnequalSize() {
        List<String> a = Arrays.asList("Red", "Green");
        List<String> b = Arrays.asList("White", "Black", "Orange");
        List<String> expected = Arrays.asList("Red", "White", "Green", "Black", "Orange");
        assertEquals(expected, App.zip(a, b));
    }

    @Test
    public void testZipEmptyList() {
        List<String> a = Arrays.asList();
        List<String> b = Arrays.asList("One", "Two");
        List<String> expected = Arrays.asList("One", "Two");
        assertEquals(expected, App.zip(a, b));
    }
}
